service: sbahn-status-update

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1 # Ireland, because SES does not exist in Frankfurt

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

plugins:
  - serverless-plugin-typescript

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'ses:SendEmail'
    Resource:
      - '*'
    Condition:
      StringEquals:
        ses:FromAddress:
          - 'daniel@schleindlsperger.de'

functions:
  scheduledHandler:
    handler: src/handler.handler
    memorySize: 128
    events:
      - schedule:
          rate: rate(1 minute)
